config/routes.rb
Ezlemon::Application.routes.draw do
  scope "/:locale", :locale => /en|cs/ do
    match "about_project" => "application#about_project", :via => "get"
    match "latest_activity" => "application#latest_activity", :via => "get"
    match "wall_of_fame" => "application#wall_of_fame", :via => "get"
  end

  resources :videos
  resources :feed_urls
  resources :documents
  resources :comments
  resources :pupils do
    get :languages
  end
  resources :teachers do
    get :languages
  end
  resources :messages
  resources :meetings do
    resources :meetings_users
  end
  resources :forums do
    resources :forum_topics do
      resources :forum_posts
    end
  end

  match "excercises/update_preview" => "excercises#update_preview", :via => "post"
  match "excercises/select_type" => "excercises#select_type", :via => "get"

  resources :excercises
  resources :excercises_results

  resources :translator, :only => [:index]
  match "translate" => "translator#translate", :via => :post

  resources :sitemap, :only => [:index]

  devise_for :users
  resources :users, :only => [:show]
  match "ajax_timezone" => "application#ajax_timezone", :via => "get"
  root :to => "application#index"

end

app/controllers/translator_controller.rb
class TranslatorController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @translator = Google::Translator.new
  end

  def translate
    if !params[:from].blank? && !params[:to].blank? && !params[:text].blank?
        @translator = Google::Translator.new
      begin
        @translated_text = @translator.translate(params[:from], params[:to], params[:text])
      rescue Google::Translator::InvalidResponse
        return render :inline => "alert('#{t(:error, :scope => [:flash, :actions, :translate])}')"
      end
    end
  end
end

app/views/translator/_form.html.erb
<%= form_tag translate_path, :remote => :true do %>
  <div class="clearfix">
    <%= text_area_tag("text", @text, :size => "70x5") %><br />
    <% from_languages = @translator.supported_languages[:from_languages].collect{|lang| [Language.language_name_from_code(lang.code.upcase), lang.code]} %>
    <% to_languages = @translator.supported_languages[:to_languages].collect{|lang| [Language.language_name_from_code(lang.code.upcase), lang.code]} %>
    <%= select_tag(:from, options_for_select(from_languages.keep_if{|lang| !lang.first.blank?}.sort_alphabetical)) %>&nbsp;&nbsp;=> &nbsp;&nbsp;
    <%= select_tag(:to, options_for_select(to_languages.keep_if{|lang| !lang.first.blank?}.sort_alphabetical)) %>
    <%= submit_tag(t(".submit")) %>
  </div>
<br />
<strong><%= t(".translation") %></strong>
  <div class="clearfix"  id="translated-text" style="overflow:auto"></div>
<% end %>

app/views/translator/index.js.erb
$( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
$( "#ui-dialog" ).dialog({
      height: 350,
      width: 550,
      title: '<%= t(".title").html_safe %>',
      modal: false
  });
initFormStyles();
$( "#ui-dialog" ).open();

app/views/translator/translate.js.erb
<% if @translated_text %>
  $("#translated-text" ).html('<%= escape_javascript(HTMLEntities.new.decode(@translated_text)) %>')
<% end %>