config/routes.rb
Ezlemon::Application.routes.draw do
  scope "/:locale", :locale => /en|cs/ do
    match "about_project" => "application#about_project", :via => "get"
    match "latest_activity" => "application#latest_activity", :via => "get"
    match "wall_of_fame" => "application#wall_of_fame", :via => "get"
  end

  resources :videos
  resources :feed_urls
  resources :documents
  resources :comments
  resources :pupils do
    get :languages
  end
  resources :teachers do
    get :languages
  end
  resources :messages
  resources :meetings do
    resources :meetings_users
  end
  resources :forums do
    resources :forum_topics do
      resources :forum_posts
    end
  end

  match "excercises/update_preview" => "excercises#update_preview", :via => "post"
  match "excercises/select_type" => "excercises#select_type", :via => "get"

  resources :excercises
  resources :excercises_results

  resources :translator, :only => [:index]
  match "translate" => "translator#translate", :via => :post

  resources :sitemap, :only => [:index]

  devise_for :users
  resources :users, :only => [:show]
  match "ajax_timezone" => "application#ajax_timezone", :via => "get"
  root :to => "application#index"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  validates :datetime_from, :presence => true
  validates :datetime_to, :presence => true
  validates :user_id, :presence => true
  
  stampable
  belongs_to :user
  has_many :meetings_users, :dependent => :destroy
  has_many :users, :through => :meetings_users
  scope :in_date_range, lambda {|from, to| where(["datetime_from >= ? AND datetime_to <= ?", from.beginning_of_day, to.end_of_day])}
  scope :for_user, lambda{|user| where(:user_id => user.assigned_user_ids)}
  record_activities :dependent => :destroy

  after_create :creator_is_attending, :notify_user, :increment_user_counter_cache
  
  def to_s(format = :short)
    I18n.t(:meeting, :scope => [:activerecord, :models]) + " - #{I18n.l(datetime_from, :format => format)} - #{I18n.l(datetime_to, :format => format)}"
  end


  def creator_is_attending
    meetings_users.create!(:user_id => user_id)
  end

  def readonly_meeting?(user)
    user.id != user_id
  end

  def notify_user
    (self.user.teachers + self.user.pupils).each do |user|
      ApplicationMailer.new_meeting(self, user).deliver
    end
  end

  def increment_user_counter_cache
    (self.user.teachers + self.user.pupils).each do |user|
      user.increment!(:unviewed_meetings_count)
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authenticate_user!
  inherit_resources

  def index
    index! do |format|
      format.json
      format.html
    end
    current_user.update_attribute(:unviewed_meetings_count, 0)
  end

  def create
    create! do |format|
      format.js
    end
  end

  def update
    update! do |format|
      format.js
    end
  end

  def show
    @meeting = Meeting.for_user(current_user).find(params[:id])
  end

  def destroy
    destroy! do |format|
      format.js
    end
  end

  private

  def collection
    @meetings =  if params[:datetime_from] && params[:datetime_to]
      from, to = Time.at(params[:datetime_from].to_i).to_date, Time.at(params[:datetime_to].to_i).to_date
      Meeting.in_date_range(from, to).for_user(current_user).select([:id, :datetime_from, :datetime_to, :notice, :user_id]).all
    else
      []
    end
  end

  def begin_of_association_chain
    current_user
  end
end

app/views/meetings/_form.erb
<div class="meeting-form">
  <%= simple_form_for(resource, :remote => true) do |f| %>

    <div class="inputs">
      <%= f.input :datetime_from, :as => :time, :input_html => {:width => 5} %>
      <%= f.input :datetime_to, :as => :time, :input_html => {:width => 5} %>
      <%= f.input :notice, :input_html => {:size => "20x2"} %>
    </div>

    <div class="hidden">
      <%= f.button :submit %>
    </div>
  <% end %>


<% unless resource.new_record? %>
    <%= t("who_will_come") %>
    <hr />
    <% resource.users.each do |user| %>
      <%= image_tag(user.small_avatar_url, :title => user) %>
    <% end %>
  <% end %>
</div>

app/views/meetings/_show.erb
<%= simple_format(resource.notice) %>

<%= t("who_will_come") %>
<hr />
<% resource.users.each do |user| %>
  <%= image_tag(user.small_avatar_url, :title => user, :alt => user) %>
<% end %>

app/views/meetings/create.js.erb
<% if @meeting.persisted? %>
  $( "#ui-dialog" ).dialog('close');
  $('#meeting-calendar').weekCalendar('refresh');
<% else %>
  $( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
<% end %>

app/views/meetings/destroy.js.erb
<% if @meeting.destroyed? %>
  $( "#ui-dialog" ).dialog('close');
  $('#meeting-calendar').weekCalendar('refresh');
<% else %>
  $( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
<% end %>

app/views/meetings/edit.js.erb
$( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
$( "#ui-dialog" ).dialog({
      height: 350,
      width: 350,
      title: '<%= t(".title").html_safe %>',
      close: function(){$('#meeting-calendar').weekCalendar("removeUnsavedEvents");},
      modal: true,
      buttons: {
        <%= t('save') %> : function(){$( "#edit_meeting_<%= @meeting.id %>" ).submit();},
        <%= t('destroy') %> : function(){
          if(confirm("<%= t(:confirmation_question) %>")){
              $.ajax({
                type: "DELETE",
                url: "<%= meeting_path(@meeting, :format => :js) %>"
            });
            }
          },
          <% users = resource.users.where(["users.id <> ?", current_user]).all %>
          <% if users.any? %>
            '<%= t('call') %>': function() {window.location.href = "skype:<%= users.collect{|u| u.skype_name}.join(";") %>?call"}
          <% end %>
        }
      });
$("input:text, textarea, select").uniform();
$( "#ui-dialog" ).open();

app/views/meetings/index.html.erb
<h1><%= t(".title") %></h1>

<br />

<div id="meeting-calendar" class="clearfix"></div>

<%= javascript_include_tag("jquery.weekcalendar", "date") %>
<%= stylesheet_link_tag("jquery.weekcalendar") %>


<script type="text/javascript">
  $(document).ready(function() {
    $('#meeting-calendar').weekCalendar({
      firstDayOfWeek: <%= t("date.first_day_of_week") %>,
      longDays: [<%= t("date.day_names").collect{|dn| "'#{dn}'"}.join(",") %>],
      shortMonths: "[<%= t("date.abbr_month_names")[1..12].collect{|mn| "'#{mn}'"}.join(",") %>]",
      newEventText: '<%= t(".new_event") %>',
      buttonText: {today:'<%= t(".today") %>'},
      use24Hour: <%= t("time.use_24_hours") %>,
      timeFormat: '<%= t("time.formats.event_time") %>',
      timeSeparator: "<%= t("time.separator") %>",
      height: function(){return 700},
      eventNew : function(calEvent, $event) {
        $.ajax({
          type: "GET",
          url: "<%= new_meeting_path(:format => :js) %>",
          data: eventTimeToParam(calEvent.start, "datetime_from") + "&" + eventTimeToParam(calEvent.end, "datetime_to")
        });
      },
      eventDrop : function(calEvent, $event) {
        $.ajax({
          type: "PUT",
          url: "<%= meetings_path %>" + "/" + calEvent.id + ".js",
          data: eventTimeToParam(calEvent.start, "datetime_from") + "&" + eventTimeToParam(calEvent.end, "datetime_to")
        });
      },
      eventResize : function(calEvent, $event) {
      
        $.ajax({
          type: "PUT",
          url: "<%= meetings_path %>" + "/" + calEvent.id + ".js",
          data: eventTimeToParam(calEvent.start, "datetime_from") + "&" + eventTimeToParam(calEvent.end, "datetime_to")
        });
      },
      eventClick : function(calEvent, $event) {
        if (calEvent.readOnly){
          $.ajax({
            type: "GET",
            url: "<%= meetings_path %>" + "/" + calEvent.id + ".js"
          })
        }
        else{
          $.ajax({
            type: "GET",
            url: "<%= meetings_path %>" + "/" + calEvent.id + "/edit.js"
          });
        }
      },
      eventMouseover : function(calEvent, $event) {
        
      },
      eventMouseout : function(calEvent, $event) {
        /*$( "#ui-dialog" ).dialog('close');*/
      },
      noEvents : function() {
        /*alert("There are no events for this week");*/
      },
      data:"<%= meetings_path(:format => :json) %>"
    });
  });

  function eventTimeToParam(time, param){
   tmp = ""
   tmp += "meeting[" + param + "(1i)]="+ time.getFullYear()
   tmp += "&meeting[" + param + "(2i)]="+ (time.getMonth() +1)
   tmp += "&meeting[" + param + "(3i)]="+ time.getDate()
   tmp += "&meeting[" + param + "(4i)]="+ time.getHours()
   tmp += "&meeting[" + param + "(5i)]="+ time.getMinutes()
   return tmp
  }
</script>

app/views/meetings/index.json.erb
<%= @meetings.map{|m| {:id => m.id, :start => m.datetime_from, :end => m.datetime_to, :title => m.notice, :readOnly => m.readonly_meeting?(current_user)}}.to_json.html_safe %>

app/views/meetings/new.js.erb
$( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
$( "#ui-dialog" ).dialog({
      height: 250,
      width: 350,
      title: '<%= t(".title").html_safe %>',
      close: function(){$('#meeting-calendar').weekCalendar("removeUnsavedEvents");},
      modal: true,
      buttons: {
        '<%= t(:cancel) %>' : function(){ $( "#ui-dialog" ).dialog('close'); },
        '<%= t(:save) %>' : function(){$( "#new_meeting" ).submit();}
        }
      });
$("input:text, textarea, select").uniform();
$( "#ui-dialog" ).open();

app/views/meetings/show.js.erb
$('#ui-dialog').html('<%= escape_javascript render(:partial => 'show') %>')
$( "#ui-dialog" ).dialog({
    height: 250,
    width: 350,
    title: '<%= t(".title").html_safe %>',
    buttons: {
      <% if meetings_user = resource.meetings_users.where(:user_id => current_user).first %>
       '<%= t('.not_attending') %>': function(){
              $.ajax({type: "DELETE", url: '<%= meeting_meetings_user_path(resource, meetings_user) %>' })
          }
        <% else %>
        '<%= t('.attending') %>': function(){
            $.ajax({type: "POST", url: '<%= meeting_meetings_users_path(resource) %>' })
        }
       <% end %>
     }
    
  });
$( "#ui-dialog" ).dialog('open');

app/views/meetings/update.js.erb
<% if @meeting.persisted? %>
  $( "#ui-dialog" ).dialog('close');
  $('#meeting-calendar').weekCalendar('refresh');
<% else %>
  $( "#ui-dialog" ).html('<%= escape_javascript(render :partial => 'form') %>')
<% end %>