config/routes.rb
Ezlemon::Application.routes.draw do
  scope "/:locale", :locale => /en|cs/ do
    match "about_project" => "application#about_project", :via => "get"
    match "latest_activity" => "application#latest_activity", :via => "get"
    match "wall_of_fame" => "application#wall_of_fame", :via => "get"
  end

  resources :videos
  resources :feed_urls
  resources :documents
  resources :comments
  resources :pupils do
    get :languages
  end
  resources :teachers do
    get :languages
  end
  resources :messages
  resources :meetings do
    resources :meetings_users
  end
  resources :forums do
    resources :forum_topics do
      resources :forum_posts
    end
  end

  match "excercises/update_preview" => "excercises#update_preview", :via => "post"
  match "excercises/select_type" => "excercises#select_type", :via => "get"

  resources :excercises
  resources :excercises_results

  resources :translator, :only => [:index]
  match "translate" => "translator#translate", :via => :post

  resources :sitemap, :only => [:index]

  devise_for :users
  resources :users, :only => [:show]
  match "ajax_timezone" => "application#ajax_timezone", :via => "get"
  root :to => "application#index"

end

app/views/activities/_activity.html.erb
<li>
  <%= link_to(image_tag(activity.actor.small_avatar_url, :class => "avatar"), activity.actor) %>
  <div class='tweetTxt'>
    <strong>
      <%= activity_icon(activity) %>
      <%= link_to(activity.actor, activity.actor) %>
      <% if activity.subject.class.name == "Comment" %>
        <%=  t("activity.comment") %>

        <% if activity.subject.commentable.class.name == 'ExcercisesResult' %>
          <% if current_user == activity.subject.commentable.teacher  %>
            <%= link_to(activity.subject.commentable, activity.subject.commentable.excercise) %>
          <% else %>
            <%= link_to(activity.subject.commentable, [:edit, activity.subject.commentable]) %>
          <% end %>
       <% else %>
          <%= link_to(activity.subject.commentable, activity.subject.commentable) %>
        <% end %>

      <% elsif activity.subject.class.name == "ExcercisesResult" %>
        <%= t("activity." + activity.action) %>

        <% if current_user == activity.subject.teacher  %>
          <%= link_to(activity.subject, activity.subject.excercise) %>
        <% else %>
          <%= link_to(activity.subject, [:edit, activity.subject]) %>
        <% end %>

      <% elsif activity.subject.class.name == "Meeting" %>
        <%= t("activity." + activity.action) %>
        <%= link_to(activity.subject, meetings_path(:start => activity.subject.datetime_from.to_i, :end => activity.subject.datetime_to.to_i)) %>
      <% elsif activity.subject.class.name == "MeetingsUser" %>
        <%= t("activity." + activity.action) %>
        <%= link_to(activity.subject.meeting, meetings_path(:start => activity.subject.meeting.datetime_from.to_i, :end => activity.subject.meeting.datetime_to.to_i)) %>
      <% elsif activity.subject.class.name == "ForumPost" %>
        <%= t("activity.forum_post") %>
        <%= link_to(activity.subject.forum_topic, forum_forum_topic_forum_posts_path(activity.subject.forum_topic.forum, activity.subject.forum_topic)) %>
      <% else %>
        <%= t("activity." + activity.action) %>
        <%= link_to(activity.subject, activity.subject) %>
      <% end %>
    </strong>
    <div class='date'>
      <%= time_ago_in_words(activity.created_at, Time.now) %>
    </div>
  </div>
  <div class='clearfix'></div>
</li>

app/views/activities/_activity_home_page.html.erb
<li>
  <%= image_tag(activity_home_page.actor.small_avatar_url, :class => "avatar", :title => activity_home_page.actor) %>
  <div class='tweetTxt'>
    <strong>
      <%= activity_icon(activity_home_page) %>
      <%= activity_home_page.actor %>
      <% if activity_home_page.subject.class.name == "Comment" %>
        <%=  t("activity.comment") %>
        <%= activity_home_page.subject.commentable %>
      <% elsif activity_home_page.subject.class.name == "ExcercisesResult" %>
        <%= t("activity." + activity_home_page.action) %>
        <%= activity_home_page.subject %>
      <% elsif activity_home_page.subject.class.name == "Meeting" %>
        <%= t("activity." + activity_home_page.action) %>
        <%= activity_home_page.subject.to_s(:time) %>
      <% elsif activity_home_page.subject.class.name == "MeetingsUser" %>
        <%= t("activity." + activity_home_page.action) %>
        <%= activity_home_page.subject.meeting.to_s(:time) %>
      <% elsif activity_home_page.subject.class.name == "ForumPost" %>
        <%= t("activity.forum_post") %>
        <%= activity_home_page.subject.forum_topic %>
      <% else %>
        <%= t("activity." + activity_home_page.action) %>
        <%= activity_home_page.subject %>
      <% end %>
    </strong>
    <div class='date'>
      <%= time_ago_in_words(activity_home_page.created_at, Time.now) %>
    </div>
  </div>
  <div class='clearfix'></div>
</li>